config/routes.rb
WebsiteRecipes::Application.routes.draw do
  resources :recipes do
    resource :comments 
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  has_many :comments 
  attr_protected :views
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < InheritedResources::Base

  def show
    @recipe = Recipe.find(params[:recipe_id])
  end 

  def new
    @recipe = Recipe.find(params[:recipe_id])
    @comment = @recipe.comments.new
    new!
  end

  def create
    @comment = Comment.new(params[:comment])
    @comment.recipe_id = params[:recipe_id]
    create!(:notice => "Dude! Nice comment.") { recipe_comments_path(@comment.recipe) }
  end
end

app/controllers/recipes_controller.rb
class RecipesController < InheritedResources::Base
  def create
    create!(:notice => "Dude! Nice job creating that recipe.") { recipes_path }
  end
  
  def update
    update!(:notice => "Dude! Nice job updating that recipe.") { recipes_path }
  end

  def show
    @recipe = Recipe.find(params[:id])
    @recipe.views += 1
    @recipe.save
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<% semantic_form_for [@recipe, @comment] do |f| %>
  <%= f.inputs :body %>
  <%= f.buttons %>
<% end %>

app/views/comments/show.html.erb
<p><%= @recipe.comments.size%> Comments:</p>
<ul>
<% @recipe.comments.each do |comment| %>
  <li><%= comment.body %></li> 
<% end %>
</ul>

<%= link_to "Add a comment", new_recipe_comments_path(@recipe) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WebsiteRecipes</title>
  <%= stylesheet_link_tag "recipestyle" %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
 <% [:info, :error, :notice ].each do |key| %>
   <% if flash[key] %>
   <div class="<%= key %>" id="flash">
     <%= flash[key] %>
   </div>
   <% end %>
 <% end %>

<%= yield %>

</body>
</html>

app/views/recipes/edit.html.erb
<% semantic_form_for @recipe do |f| %>
  <%= f.inputs :name, :source, :cuisine, :main_ingredient, :ingredients, :directions %>
  <%= f.buttons %> 
<% end %>

app/views/recipes/index.html.erb
<h1>Recipes</h1>

<table>
  <% @recipes.each do |recipe| %>
    <tr>
      <td><%= link_to recipe.name, recipe_path(recipe) %> </td>
      <td><%= link_to "Edit", edit_recipe_path(recipe) %></td>
      <td><%= button_to "Delete", recipe_path(recipe), :method => :delete %></td> 
    </tr>
  <% end %>
</table>


<%= link_to "Add a new recipe", new_recipe_path %>

app/views/recipes/new.html.erb
<% semantic_form_for @recipe do |f| %>
  <%= f.inputs %>
  <%= f.buttons %> 
<% end %>

app/views/recipes/show.html.erb
<h1><%= @recipe.name %></h1>

<p>Source: <%= @recipe.source %> </p>
<p>Ingredients: <%= @recipe.ingredients %> </p>
<p>Directions: <%= @recipe.directions %> </p>
<p>Main Ingredient: <%= @recipe.main_ingredient %> </p>
<p>Cuisine : <%= @recipe.cuisine %> </p>
<p>Created : <%= @recipe.created_at %> </p>
<p>Last Updated : <%= @recipe.updated_at %> </p>
<p>Views : <%= @recipe.views %> </p>

<p><%= @recipe.comments.size%> Comments:</p>
<ul>
<% @recipe.comments.each do |comment| %>
  <li><%= comment.body %></li> 
<% end %>
</ul>

<%= link_to "Add a comment", new_recipe_comments_path(@recipe) %>